name: tests
on:
  push:
  pull_request:

jobs:
  test-php-74:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Guzzle 6
        run: composer require guzzlehttp/guzzle:^6.0 --no-interaction

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Execute tests
        run: composer tests
